### ISSUE TITLE
Local server throws Invalid signature error after updating to 1.3.1 from 1.2.0

### ISSUE THREAD

**Issue by tiwac100** [inngest/inngest-js#112]
After updating from 1.2.0 to 1.3.1 today the local dev server stopped processing functions with this error (nothing else in the application was changed):
```
4:06PM INF output > step output attempt=2 edge={"incoming":"step","outgoing":"$trigger"} fn_id=app-push-to-channel fn_name="Push to channel" generator=null output={"body":{"__serialized":true,"message":"Invalid signature","name":"Error","stack":"Error: Invalid signature\n    at RequestSignature.verifySignature (.../nextjs/node_modules/inngest/components/InngestCommHandler.js:627:19)\n    at InngestCommHandler.validateSignature (.../nextjs/node_modules/inngest/components/InngestCommHandler.js:556:35)\n    at InngestCommHandler.handleAction (.../nextjs/node_modules/inngest/components/InngestCommHandler.js:257:22)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ServerTiming.wrap (.../nextjs/node_modules/inngest/helpers/ServerTiming.js:70:20)\n    at async .../nextjs/node_modules/inngest/components/InngestCommHandler.js:232:31\n    at async Object.apiResolver (.../nextjs/node_modules/next/dist/server/api-utils/node.js:372:9)\n    at async DevServer.runApi (.../nextjs/node_modules/next/dist/server/next-server.js:513:9)\n    at async Object.fn (.../nextjs/node_modules/next/dist/server/next-server.js:815:35)\n    at async Router.execute (.../nextjs/node_modules/next/dist/server/router.js:243:32)\n    at async DevServer.runImpl (.../nextjs/node_modules/next/dist/server/base-server.js:432:29)\n    at async DevServer.run (.../nextjs/node_modules/next/dist/server/dev/next-dev-server.js:814:20)\n    at async DevServer.handleRequestImpl (.../nextjs/node_modules/next/dist/server/base-server.js:375:20)\n    at async .../nextjs/node_modules/next/dist/server/base-server.js:157:99","type":"internal"},"status":500} run_id=01GTC8Y2TR17DQFJK0KS6CDVWA step=step
```

My `INNGEST_SIGNING_KEY` environment variable is set to the test key value.

The event trigger:
```
await inngest.send({ name: 'app/vote.created', data: { vote } });
```

The function:
```
export default inngest.createFunction(
  {
    name: 'Push to channel',
    throttle: {
      key: 'rank-{{ event.data.vote.channelId }}',
      count: 1,
      period: '1s',
    },
  },
  { event: 'app/vote.created' },
  async ({ event }) => {
    // ...
  }
);
```

**Comment by tiwac100** [comment]
Downgrading to 1.2.0 fixed the issue.

**Comment by jpwilliams** [comment]
@tiwac100 Couple of regressiony issues surfaced following `1.3.0`! Thanks for reporting.

Fixing this and another regression in `1.3.2` tomorrow!
