### ISSUE TITLE
[BUG] Could not find an event key to send events

### ISSUE THREAD

**Issue by pullmann4rent** [inngest/inngest-js#144]
Hello,

I opened my cmd and called this command: npx inngest-cli@latest dev

then I installed in my remix folder npm i inngest --save

if I start my server then I got everytime and every 5 or 10 seconds this:

```
Could not find an event key to send events; sending will throw unless an event key is added. Please pass one to the constructor, set the INNGEST_EVENT_KEY environment variable, or use inngest.setEventKey() at runtime.
No routes matched location "/x/inngest" 
Warning: A title element received an array with more than 1 element as children. In browsers title Elements can only have Text Nodes as children. If the 
children being rendered output more than a single text node in aggregate the browser will display markup and comments as text in the title and hydration 
will likely fail and fall back to client rendering
    at title
    at head
    at html
    at CatchBoundary (C:\sp\folder_bk\es\es\build\index.js:411:43)
    at RemixCatchBoundary (C:\sp\folder_bk\es\es\node_modules\@remix-run\react\dist\errorBoundaries.js:140:10)
    at RemixRouteError (C:\sp\folder_bk\es\es\node_modules\@remix-run\react\dist\components.js:84:3)
    at RenderErrorBoundary (C:\sp\folder_bk\es\es\node_modules\react-router\dist\umd\react-router.development.js:624:7)
    at Routes (C:\sp\folder_bk\es\es\node_modules\react-router\dist\umd\react-router.development.js:1174:7)
    at Router (C:\sp\folder_bk\es\es\node_modules\react-router\dist\umd\react-router.development.js:1106:17)
    at StaticRouterProvider (C:\sp\folder_bk\es\es\node_modules\react-router-dom\server.js:67:3)
    at RemixErrorBoundary (C:\sp\folder_bk\es\es\node_modules\@remix-run\react\dist\errorBoundaries.js:24:5)
    at RemixServer (C:\sp\folder_bk\es\es\node_modules\@remix-run\react\dist\server.js:47:3)
GET /x/inngest 404 - - 49.805 ms
Could not find an event key to send events; sending will throw unless an event key is added. Please pass one to the constructor, set the INNGEST_EVENT_KEY environment variable, or use inngest.setEventKey() at runtime.
No routes matched location "/.netlify/functions/inngest" 
Warning: A title element received an array with more than 1 element as children. In browsers title Elements can only have Text Nodes as children. If the 
children being rendered output more than a single text node in aggregate the browser will display markup and comments as text in the title and hydration 
will likely fail and fall back to client rendering
    at title
    at head
    at html
    at CatchBoundary (C:\sp\folder_bk\es\es\build\index.js:411:43)
    at RemixCatchBoundary (C:\sp\folder_bk\es\es\node_modules\@remix-run\react\dist\errorBoundaries.js:140:10)
    at RemixRouteError (C:\sp\folder_bk\es\es\node_modules\@remix-run\react\dist\components.js:84:3)
    at RenderErrorBoundary (C:\sp\folder_bk\es\es\node_modules\react-router\dist\umd\react-router.development.js:624:7)
    at Routes (C:\sp\folder_bk\es\es\node_modules\react-router\dist\umd\react-router.development.js:1174:7)
    at Router (C:\sp\folder_bk\es\es\node_modules\react-router\dist\umd\react-router.development.js:1106:17)
    at StaticRouterProvider (C:\sp\folder_bk\es\es\node_modules\react-router-dom\server.js:67:3)
    at RemixErrorBoundary (C:\sp\folder_bk\es\es\node_modules\@remix-run\react\dist\errorBoundaries.js:24:5)
    at RemixServer (C:\sp\folder_bk\es\es\node_modules\@remix-run\react\dist\server.js:47:3)
GET /.netlify/functions/inngest 404 - - 51.139 ms
Could not find an event key to send events; sending will throw unless an event key is added. Please pass one to the constructor, set the INNGEST_EVENT_KEY environment variable, or use inngest.setEventKey() at runtime.
No routes matched location "/.redwood/functions/inngest" 
Warning: A title element received an array with more than 1 element as children. In browsers title Elements can only have Text Nodes as children. If the 
children being rendered output more than a single text node in aggregate the browser will display markup and comments as text in the title and hydration 
will likely fail and fall back to client rendering
    at title
    at head
    at html
    at CatchBoundary (C:\sp\folder_bk\es\es\build\index.js:411:43)
    at RemixCatchBoundary (C:\sp\folder_bk\es\es\node_modules\@remix-run\react\dist\errorBoundaries.js:140:10)
    at RemixRouteError (C:\sp\folder_bk\es\es\node_modules\@remix-run\react\dist\components.js:84:3)
    at RenderErrorBoundary (C:\sp\folder_bk\es\es\node_modules\react-router\dist\umd\react-router.development.js:624:7)
    at Routes (C:\sp\folder_bk\es\es\node_modules\react-router\dist\umd\react-router.development.js:1174:7)
    at Router (C:\sp\folder_bk\es\es\node_modules\react-router\dist\umd\react-router.development.js:1106:17)
    at StaticRouterProvider (C:\sp\folder_bk\es\es\node_modules\react-router-dom\server.js:67:3)
    at RemixErrorBoundary (C:\sp\folder_bk\es\es\node_modules\@remix-run\react\dist\errorBoundaries.js:24:5)
    at RemixServer (C:\sp\folder_bk\es\es\node_modules\@remix-run\react\dist\server.js:47:3)
GET /.redwood/functions/inngest 404 - - 54.012 ms
Could not find an event key to send events; sending will throw unless an event key is added. Please pass one to the constructor, set the INNGEST_EVENT_KEY environment variable, or use inngest.setEventKey() at runtime.
```

Why I am getting this error ?

**Comment by jpwilliams** [comment]
Hi @pullmann4rent!

Looks like the warning you're seeing is:

> Could not find an event key to send events; sending will throw unless an event key is added. Please pass one to the constructor, set the `INNGEST_EVENT_KEY` environment variable, or use `inngest.setEventKey()` at runtime.

When calling `new Inngest()`, this warning is shown when the library can't detect an event key from the `INNGEST_EVENT_KEY` environment variable. An event key is a unique key that allows your application to send (aka publish) events securely to Inngest.

Head to the [Creating an event key](https://www.inngest.com/docs/events/creating-an-event-key) docs to see how to get one and specify it in your app! 🙂

**Comment by jpwilliams** [comment]
I see someone helped you out on our Discord with this, so I'll close. :)
