### ISSUE TITLE
[BUG] TypeError: Body has already been used 

### ISSUE THREAD

**Issue by psteinroe** [inngest/inngest-js#586]
**Describe the bug**
We are seeing error logs coming from Inngest thrown in `getResponseError` because the body has already been used. I do not know what the root error is, and is happening rarely, but I am a bit afraid this can lead to loss of data because we rely on inngest to be accepting events at all times. The full error is:
```
TypeError: Body has already been used. It can only be used once. Use tee() first if you need to read it twice. at Gl.getResponseError (index.js:25:50970) at Gl._send (index.js:25:53022) at async index.js:25:315335 at async Promise.all (index 0) at async index.js:25:315291 at async Promise.all (index 0) at async index.js:25:315244 at async i (index.js:25:229977) at async i (index.js:25:229977) at async index.js:25:246409
```

**To Reproduce**
Repeatedly send events to inngest. We are running in cf worker.

**Comment by kwerdna19** [comment]
I just want to voice that I am running into this and although I dont think its the main issue, it is making things harder to debug.

Can the [fix PR](https://github.com/inngest/inngest-js/pull/745) be merged at some point?

thank you

**Comment by kwerdna19** [comment]
In case anyone is running into this while self hosting I’ll say what the issue was for me.

The error was a result of a sendEvent fetch request which was returning html instead of JSON and thus failing to parse as json which led to the error handling code trying to read the body again.

I’m pretty sure the culprit for me was my Inngest secrets (signing key and event key) containing symbols like a `/` she maybe `=`. When I changed my secret to just be alphanumeric + underscores it started working again.

Hope this helps someone
